apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    project: expense
    env: dev
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      project: expense
      env: dev
      tier: frontend
  template:
    metadata:
      labels:
        project: expense
        env: dev
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: sunil0428/app2:v1
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    project: expense
    env: dev
    tier: frontend
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007