apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    project: expense
    env: dev
    tier: db
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      project: expense
      env: dev
      tier: db
  template:
    metadata:
      labels:
        project: expense
        env: dev
        tier: db
    spec:
      containers:
      - name: mysql
        image: sunil0428/my_mysql:v1
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    project: expense
    env: dev
    tier: db
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306