apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::423623871433:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-0WJpRj1RMpPM
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      -:expense-trainee
      userarn: arn:aws:iam::423623871433:user/sunil
      username: sunil
kind: ConfigMap
metadata:
  creationTimestamp: "2024-12-12T14:49:28Z"
  name: aws-auth
  namespace: kube-system
  uid: 319b6b90-9407-41a8-87b3-706fa1fbabbd