apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: expense
  name: expense-trainee
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: expense-trainee
  namespace: expense
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role #this must be Role or ClusterRole
  name: expense-trainee # this must match the name of the Role or ClusterRole you wish to bind to
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: sunil # "name" is case sensitive

  