apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    project: expense
    env: dev
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      project: expense
      env: dev
      tier: frontend
  template:
    metadata:
      labels:
        project: expense
        env: dev
        tier: frontend
    spec:
      containers:
      - name: app1
        image: sunil0428/app1:v1
---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    project: expense
    env: dev
    tier: frontend
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: 80